[ui]
pager = "delta"
conflict-marker-style = "git"
diff-formatter = ":git"
diff-editor = ":builtin"

[user]
name = "Aru Sahni"
email = "aru@arusahni.net"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
