#!/bin/zsh
# This hook is run after every virtualenv is activated.
PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT=${RPROMPT-${RPS1-default}}
# _OLD_RPROMPT="$RPROMPT"
RPROMPT="%{$(echotc UP 1)%}$PR_RED$(virtualenv_info)%{$(echotc DO 1)%}$PR_NO_COLOR $_OLD_RPROMPT"
